source 'https://rubygems.org'
#ruby '2.3.0'
gem 'rails', '4.2.6'
gem 'sass-rails'
gem 'sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'barista'
gem 'jquery-rails', '~> 4.0.4'
gem 'sprockets-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'execjs'
gem 'therubyracer', :platforms => :ruby
gem 'less-rails', '~> 2.7', '>= 2.7.1'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry-rails'
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'puma'
  gem 'tunemygc'
  gem 'rack-mini-profiler'
  gem 'flamegraph'
  gem 'stackprof'
end

gem 'bootstrap-sass'
gem 'devise'
gem 'devise_ldap_authenticatable'
gem 'redis-rails'
gem 'devise_cas_authenticatable', git: 'https://github.com/jpamaya/devise_cas_authenticatable'
gem 'high_voltage'
gem 'mysql2', '~> 0.3.20'
gem 'simple_form'
gem 'mail_form'
gem 'cocoon'
gem 'active_link_to'
gem 'non-stupid-digest-assets'
gem 'enumerize'
gem 'enum_help'
gem 'friendly_id', '~> 5.1.0' #Needs to be >5.0.0
gem 'chartkick'
gem 'rolify'
gem 'authority'
gem 'simple-navigation'
gem 'simple-navigation-bootstrap'
gem 'annotate'
gem 'gmaps4rails'
gem 'geocoder'
gem 'rmagick'
gem 'rest-client'
gem 'nokogiri' #compatible with ruby version 2.3.0
gem 'gretel'
gem 'sprockets', '3.6.3'
gem 'open-weather'
gem 'carrierwave', '~> 0.10.0'
gem 'mini_magick', '~> 4.3'
gem 'will_paginate'
gem 'ckeditor'
gem 'has_scope'
gem 'lightbox-bootstrap-rails'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'delayed_job_active_record'
gem 'browser'
gem 'countdown'

group :production do
  gem 'rails_12factor'
end