// Generated by CoffeeScript 1.10.0
(function() {
  $(".submit").on("focusout", function() {
    var currentUrl, preview;
    preview = $("#preview-url");
    currentUrl = $.trim(this.url);
    return preview.show().attr('src', currentUrl);
  });

}).call(this);
